name: deploy node js application
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            git config --global --add safe.directory /home/vidzai/source/nodeserver
            cd /home/vidzai/source/nodeserver
            git pull origin master
            docker compose up -d